Ball tracking
bit-bots/bitbots_behavior pull request #96
Opened 2020-11-14 10:03 UTC by NFiedler

## Proposed changes
Track the ball in the odom frame or in the map frame depending on the precision of the odometry.
Addresses #33. Waits for #72 .
The ball should be saved in the map- as well as the odom-frame, so we can decide which to use based on the current state of the localization.

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2020-11-14 15:09 UTC, timonegk approved these changes

2020-11-14 15:30 UTC, timonegk requested changes
I just tested this and there are still problems because the goal is somehow interpreted as relative

2020-11-16 09:32 UTC, NFiedler commented
@timonegk it seems like this problem occurs on the master branch too :( 
Can we merge this and handle that in another isse?

2020-11-16 09:44 UTC, timonegk approved these changes

2020-11-16 09:49 UTC, merged